name: Nodejs Github Action

on: push

jobs:
  build:
    runs-on: unbuntu-latest

    steps: 
      - uses: action/checkout@v3  # checkout the repository
      - name: Use Node

        uses: action/checkout@v3  # checkout the repository
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
